---
title: "Parte B: SVM"
output: html_document
author: "Micaela Del Longo @MicaKil"
---

```{r}
# Cargar las bibliotecas necesarias
library(e1071)  # Para SVM
library(caret)  # Para preprocesamiento y evaluación del modelo
```

```{r}

data <- read.csv("data/data-parte-b/arbolado-mza-dataset.csv")
data$ultima_modificacion <- NULL
data$area_seccion <- NULL

test_data <- read.csv("data/data-parte-b/arbolado-mza-dataset-test.csv")
test_data$ultima_modificacion <- NULL
test_data$area_seccion <- NULL
```

```{r}
train_data$inclinacion_peligrosa <- as.factor(train_data$inclinacion_peligrosa)

x <- select(train_data, -inclinacion_peligrosa)
y <- train_data$inclinacion_peligrosa

svm_ctrl <- tune.control(sampling = "cross",
             cross = 10,
             best.model = TRUE,
             performance = TRUE)

svm_tune <- tune.svm(formula = inclinacion_peligrosa ~ circ_tronco_cm + lat + long + peligrosidad_especie + peligrosidad_diametro + peligrosidad_altura + peligrosidad_seccion,
                     x = x,
                     y = y,
                     data = train_data,
                     tunecontrol = svm_ctrl)

best.model <- svm_tune$best.model

svm_model <- svm(inclinacion_peligrosa ~ circ_tronco_cm + lat + long + peligrosidad_especie + peligrosidad_diametro + peligrosidad_altura + peligrosidad_seccion,
                 data = train_data,
                 kernel = "radial",
                 cost = 1,
                 cross = 5,
                 type = "C-classification")

predictions <- predict(best.model, newdata = test_data)
predictions_numeric <- as.numeric(as.character(predictions)) # predictions es un factor, hay que pasarlo a numeric
```

```{r}
result_dataset <- data.frame(id = test_data$id, inclinacion_peligrosa = predictions_numeric)
write.csv(result_dataset, "data/submissions/submission_21.csv", row.names = FALSE)
```


```{r}
sub20 <- read.csv("data/submissions/submission_20.csv")
percent <- sum(sub20$inclinacion_peligrosa == 1) / nrow(sub20) * 100
print(percent)

percent_prediction <- sum(predictions_numeric == 1) / length(predictions_numeric) * 100
print(percent_prediction)
```

```
